
fullnameOverride: "downloader"

replicaCount: 1

envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: downloader-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "32Mi"

podSecurityContext:
  runAsUser: 65534 # nobody
  fsGroup: 65534 # nobody

containers:
  - name: downloader
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: downloader-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        memory: 64Mi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?
    env:
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_DOWNLOADER_PORT: "4587"
      # CYBER_DOJO_K8S_PORT: "19661"
